// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright © 2026 SirOtter0 and INFINILECT contributors.
package org.infinilect.app.epub

import java.nio.ByteBuffer
import java.util.zip.CRC32
import java.io.ByteArrayOutputStream
import java.awt.image.BufferedImage
import javax.imageio.ImageIO
import javax.imageio.IIOImage
import javax.imageio.ImageWriteParam
import javax.imageio.stream.MemoryCacheImageOutputStream
import kotlin.test.*
import org.infinilect.app.reader.epub.EpubImagePolicy

/** Shared preflight only: these host tests do NOT execute Android BitmapFactory. */
class EpubRasterHeaderTest {
    private fun png(width: Int = 96, height: Int = 64): ByteArray = developmentPng().also {
        ByteBuffer.wrap(it).putInt(16, width).putInt(20, height)
        ByteBuffer.wrap(it).putInt(29, CRC32().apply { update(it, 12, 17) }.value.toInt())
    }
    @Test fun originalPngDimensionsAreInspectedBeforeDecode() { assertEquals(96 to 64, epubRasterDimensions(developmentPng(), "image/png")) }
    @Test fun originalJpegDimensionsAreInspectedBeforeDecode() { assertEquals(96 to 64, epubRasterDimensions(developmentJpeg(), "image/jpeg")) }
    @Test fun maximumDimensionsAndPixelsPassPreflight() { assertEquals(2048 to 512, epubRasterDimensions(png(2048, 512), "image/png")) }
    @Test fun excessiveWidthIsRejectedBeforePixelAllocation() { assertFailsWith<IllegalArgumentException> { epubRasterDimensions(png(2049, 1), "image/png") } }
    @Test fun excessiveHeightIsRejectedBeforePixelAllocation() { assertFailsWith<IllegalArgumentException> { epubRasterDimensions(png(1, 2049), "image/png") } }
    @Test fun excessiveTotalPixelsIsRejectedBeforePixelAllocation() { assertFailsWith<IllegalArgumentException> { epubRasterDimensions(png(2048, 513), "image/png") } }
    @Test fun negativeOrOverflowDimensionsAreRejected() { for (width in listOf(-1, Int.MAX_VALUE, 0)) assertFailsWith<IllegalArgumentException> { epubRasterDimensions(png(width, 10), "image/png") } }
    @Test fun wrongDeclaredMimeIsRejected() { assertFailsWith<IllegalArgumentException> { epubRasterDimensions(developmentPng(), "image/jpeg") }; assertFailsWith<IllegalArgumentException> { epubRasterDimensions(developmentJpeg(), "image/png") } }
    @Test fun unsupportedSvgIsNeverPassedToDecoder() { assertFails { epubRasterDimensions("<svg/>".encodeToByteArray(), "image/svg+xml") } }
    @Test fun encodedByteLimitIsEnforcedBeforeHeaderParsing() { assertFailsWith<IllegalArgumentException> { epubRasterDimensions(ByteArray(EpubImagePolicy.ENCODED_BYTES + 1), "image/png") } }
    @Test fun truncatedPngAndJpegAreRejected() { for ((bytes, type) in listOf(developmentPng() to "image/png", developmentJpeg() to "image/jpeg")) for (n in listOf(0, 1, 20, bytes.size - 1)) assertFails { epubRasterDimensions(bytes.copyOf(n), type) } }
    @Test fun corruptPngCrcIsRejected() { val bytes = developmentPng(); bytes[40] = (bytes[40].toInt() xor 1).toByte(); assertFails { epubRasterDimensions(bytes, "image/png") } }
    @Test fun maliciousPngChunkSizeCannotOverflow() { val bytes = developmentPng(); ByteBuffer.wrap(bytes).putInt(33, Int.MAX_VALUE); assertFails { epubRasterDimensions(bytes, "image/png") } }
    @Test fun appendedDataAndProfileChunksAreRejected() {
        assertFails { epubRasterDimensions(developmentPng() + byteArrayOf(0), "image/png") }
        val bytes = developmentPng(); "iCCP".encodeToByteArray().copyInto(bytes, 37)
        assertFails { epubRasterDimensions(bytes, "image/png") }
    }
    @Test fun jpegProfileOrExifSegmentsAreRejected() {
        val bytes = developmentJpeg(); bytes[3] = 0xe1.toByte()
        assertFails { epubRasterDimensions(bytes, "image/jpeg") }
    }
    @Test fun jpegSegmentLengthCannotEscapeBuffer() {
        val bytes = developmentJpeg(); bytes[4] = 0xff.toByte(); bytes[5] = 0xff.toByte()
        assertFails { epubRasterDimensions(bytes, "image/jpeg") }
    }
    @Test fun originalArtworkIsDeterministic() { assertContentEquals(developmentPng(), developmentPng()); assertContentEquals(developmentJpeg(), developmentJpeg()) }
    @Test fun jpegProfileBetweenEntropyScansIsAlsoRejected() {
        val bytes = developmentJpeg()
        val injected = bytes.copyOf(bytes.size - 2) + byteArrayOf(0xff.toByte(), 0xe1.toByte(), 0, 2, 0xff.toByte(), 0xd9.toByte())
        assertFails { epubRasterDimensions(injected, "image/jpeg") }
    }

    @Test fun progressiveJpegMultipleEntropyScansPassBoundedPreflight() {
        assertEquals(8 to 8, epubRasterDimensions(originalProgressiveJpeg(), "image/jpeg"))
    }

}


/** Original constant-color host fixture, generated by the JDK; not an Android decoder test. */
internal fun originalProgressiveJpeg(): ByteArray {
    val writer = ImageIO.getImageWritersByFormatName("JPEG").next()
    val pixels = BufferedImage(8, 8, BufferedImage.TYPE_INT_RGB)
    return try {
        ByteArrayOutputStream().use { bytes ->
            MemoryCacheImageOutputStream(bytes).use { output ->
                writer.output = output
                val options = writer.defaultWriteParam.apply { progressiveMode = ImageWriteParam.MODE_DEFAULT }
                writer.write(null, IIOImage(pixels, null, null), options)
            }
            bytes.toByteArray()
        }
    } finally { writer.dispose(); pixels.flush() }
}
